<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SAPTEST_A00" name="Test" tests="4" failures="1" timestamp="17 Aug 2017 14:12:32 GMT" time="10.027" errors="0">
  <testcase name="NuevosAlumnos" time="1.292" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumnos" time="1.709" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Alumni" time="1.361" classname="Salle.TestClasses.SalleHeader"/>
  <testcase name="Empresas" time="0.534" classname="Salle.TestClasses.SalleHeader">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at Salle.TestClasses.SalleHeader.Empresas(SalleHeader.java:96)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- Empresas -->
</testsuite> <!-- Test -->
